name: 'automerge'
on:
  check_suite:         {types: ['completed']}
  pull_request:        {}
  pull_request_review: {types: ['submitted']}
  status:              {}

jobs:
  automerge:
    runs-on: 'ubuntu-latest'
    permissions:
      contents:      'write'
      pull-requests: 'write'
    steps:
      - uses: 'pascalgn/automerge-action@v0.16.4'
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          MERGE_LABELS: ''
          MERGE_METHOD: 'squash'
          MERGE_REQUIRED_APPROVALS: 1
