name: 'automerge'
on:   'pull_request'
permissions:
  contents:      'write'
  pull-requests: 'write'

jobs:
  automerge:
    runs-on: 'ubuntu-latest'
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve      ${{github.event.pull_request.html_url}}
          gh pr merge --auto --rebase ${{github.event.pull_request.html_url}}
